
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sukhm
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public Game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        player = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        end = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(null);

        player.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/player.jpg"))); // NOI18N
        player.setText("jLabel2");
        player.setMaximumSize(new java.awt.Dimension(15, 15));
        player.setMinimumSize(new java.awt.Dimension(0, 0));
        player.setPreferredSize(new java.awt.Dimension(5, 5));
        player.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                playerMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                playerMouseMoved(evt);
            }
        });
        getContentPane().add(player);
        player.setBounds(330, 250, 25, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 90, 50, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 290, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");
        jLabel4.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 290, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 140, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel6.setText("jLabel2");
        jLabel6.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 290, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel7.setText("jLabel2");
        jLabel7.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 240, 50, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel8.setText("jLabel2");
        jLabel8.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 40, 50, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 40, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel10.setText("jLabel2");
        jLabel10.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 40, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel11.setText("jLabel2");
        jLabel11.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(20, 140, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel12.setText("jLabel2");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 190, 50, 50);

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/start_tile.jpg"))); // NOI18N
        start.setText("jLabel2");
        start.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(start);
        start.setBounds(320, 240, 50, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel14.setText("jLabel2");
        jLabel14.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 290, 50, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel15.setText("jLabel2");
        jLabel15.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel15);
        jLabel15.setBounds(220, 290, 50, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel16.setText("jLabel2");
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel16);
        jLabel16.setBounds(270, 290, 50, 50);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel17.setText("jLabel2");
        jLabel17.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(320, 290, 50, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel18.setText("jLabel2");
        jLabel18.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(220, 40, 50, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel19.setText("jLabel2");
        jLabel19.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(270, 140, 50, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel20.setText("jLabel2");
        jLabel20.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(120, 190, 50, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel21.setText("jLabel2");
        jLabel21.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel21);
        jLabel21.setBounds(120, 90, 50, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel22.setText("jLabel2");
        jLabel22.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(120, 40, 50, 50);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel23.setText("jLabel2");
        jLabel23.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel23);
        jLabel23.setBounds(20, 40, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel24.setText("jLabel2");
        jLabel24.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel24);
        jLabel24.setBounds(70, 40, 50, 50);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel25.setText("jLabel2");
        jLabel25.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel25);
        jLabel25.setBounds(120, 140, 50, 50);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel26.setText("jLabel2");
        jLabel26.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel26);
        jLabel26.setBounds(220, 240, 50, 50);

        end.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finish_tile.jpg"))); // NOI18N
        end.setText("jLabel2");
        end.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(end);
        end.setBounds(20, 90, 50, 50);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel29.setText("jLabel2");
        jLabel29.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel29);
        jLabel29.setBounds(320, 190, 50, 50);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wall_tile.jpg"))); // NOI18N
        jLabel30.setText("jLabel2");
        jLabel30.setPreferredSize(new java.awt.Dimension(50, 50));
        getContentPane().add(jLabel30);
        jLabel30.setBounds(170, 140, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jLabel1.setName(""); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//
    private void playerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerMouseMoved


    }//GEN-LAST:event_playerMouseMoved

    private void checkGameOver(JLabel l){
        if((player.getX()<=(l.getX()+l.getWidth()))
                &&(player.getX()>=(l.getX()))
                    &&(player.getY()<=(l.getY()+l.getHeight()))
                        &&(player.getY()>=(l.getY()))
                ){
            JOptionPane.showMessageDialog(null,"Game Over");
            System.exit(0);
        }
    }
    
    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        Point p = MouseInfo.getPointerInfo().getLocation();
        player.setLocation((int) (p.getX() - player.getWidth()), (int) (p.getY() - 3*player.getHeight()/2));
        checkGameOver(jLabel2);
        checkGameOver(jLabel3);
        checkGameOver(jLabel4);
        checkGameOver(jLabel5);
        checkGameOver(jLabel6);
        checkGameOver(jLabel7);
        checkGameOver(jLabel8);
        checkGameOver(jLabel9);
        checkGameOver(jLabel10);
        checkGameOver(jLabel11);
        checkGameOver(jLabel12);
        checkGameOver(jLabel14);
        checkGameOver(jLabel15);
        checkGameOver(jLabel16);
        checkGameOver(jLabel17);
        checkGameOver(jLabel18);
        checkGameOver(jLabel19);
        checkGameOver(jLabel20);
        checkGameOver(jLabel21);
        checkGameOver(jLabel22);
        checkGameOver(jLabel23);
        checkGameOver(jLabel24);
        checkGameOver(jLabel25);
        checkGameOver(jLabel26);
        checkGameOver(jLabel29);
        checkGameOver(jLabel30);
        if((player.getX()<=(end.getX()+end.getWidth()))
                &&(player.getX()>=(end.getX()))
                    &&(player.getY()<=(end.getY()+end.getHeight()))
                        &&(player.getY()>=(end.getY()))
                ){
            JOptionPane.showMessageDialog(null,"You Won!");
            System.exit(0);
        }
    }//GEN-LAST:event_formMouseMoved

    private void playerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerMouseDragged

    }//GEN-LAST:event_playerMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Game().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel end;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel player;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
